/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServerServerKeySessionSessionIdRouteImport } from './routes/server.$serverKey.session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerKeySessionSessionIdRoute =
  ServerServerKeySessionSessionIdRouteImport.update({
    id: '/server/$serverKey/session/$sessionId',
    path: '/server/$serverKey/session/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/server/$serverKey/session/$sessionId': typeof ServerServerKeySessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/server/$serverKey/session/$sessionId': typeof ServerServerKeySessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/server/$serverKey/session/$sessionId': typeof ServerServerKeySessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/new' | '/settings' | '/server/$serverKey/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/settings' | '/server/$serverKey/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/settings'
    | '/server/$serverKey/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  ServerServerKeySessionSessionIdRoute: typeof ServerServerKeySessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverKey/session/$sessionId': {
      id: '/server/$serverKey/session/$sessionId'
      path: '/server/$serverKey/session/$sessionId'
      fullPath: '/server/$serverKey/session/$sessionId'
      preLoaderRoute: typeof ServerServerKeySessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  ServerServerKeySessionSessionIdRoute: ServerServerKeySessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
